# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/vivado_synth/vivado_synth.cache/wt [current_project]
set_property parent.project_path C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/vivado_synth/vivado_synth.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/vivado_synth/vivado_synth.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/DFlipFlop.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/FullAdder.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/FullAdderSubtractor.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/IIR.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/Reg.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/RippleCarryAdder.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/RippleCarryAdderSubtractor.vhd
  C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/db/src/IIR16bit.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/vivado_synth/vivado_synth.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/gabriele/Documents/DigitalSystems/ProjectIIR/vivado_synth/vivado_synth.srcs/constrs_1/new/constraints.xdc]


synth_design -top IIR16bit -part xc7z010clg400-3


write_checkpoint -force -noxdef IIR16bit.dcp

catch { report_utilization -file IIR16bit_utilization_synth.rpt -pb IIR16bit_utilization_synth.pb }
